### ISSUE TITLE
rework footer

### ISSUE THREAD

**Issue by Nils-Magnus** [opentelekomcloud/LoveOTC#71]
change logo in footer to "T + Open\nTelekom\Cloud" (in Magenta/white/Magenta).

Logo is attached.
![OTC-Logo-2024](https://github.com/opentelekomcloud/LoveOTC/assets/1684438/51786e4e-45d8-4f65-8b3a-f1b1d7a1e189)

The black footer box should be vertically shorter.

**Comment by Aloento** [comment]
https://github.com/opentelekomcloud/LoveOTC/commit/09f9e71dfe33dad31b92036e334cff7094d5cf11
