### ISSUE TITLE
use correct Font

### ISSUE THREAD

**Issue by Nils-Magnus** [opentelekomcloud/LoveOTC#73]
Just use fonts of the "TeleNeo" font family, either in Bold or Regular.

Use the font package v1.8. [T_teleneo_v1_8.zip](https://github.com/opentelekomcloud/LoveOTC/files/14037566/T_teleneo_v1_8.zip)

For the shop just use the web font in WOFF, WOFF2 or EOT formats.

Make the "TeleNeo" font family the priority of all other fonts.

**Comment by Aloento** [comment]
https://github.com/opentelekomcloud/LoveOTC/commit/41ff27337420ae9cd4a7e8588c97c7aee23ca186

**Comment by Nils-Magnus** [comment]
approved
